# Exports

export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:$HOME/.emacs.d/bin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/go/bin

# Functions

function source_path {
    [ -f $1 ] && source $1
}


# Sources

source_path $HOME/.cargo/env
source_path $HOME/.config/alacritty/extra/completions/alacritty.bash 
source_path $HOME/.config/bash/aliases


# Anything that needs to be done at the end 
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

eval "$(starship init bash)"

