#!/usr/bin/env bash

source "$HOME/.config/bash/functions"

# Exports
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:$HOME/.emacs.d/bin
export PATH=$PATH:$HOME/.dotnet/

export MANROFFOPT="-c"

# Get the colors in the opened man page itself (this is for fman)
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

export NVM_DIR="$HOME/.nvm"

# Sources
source_path "$HOME/.cargo/env"
source_path "$HOME/.config/alacritty/extra/completions/alacritty.bash"
source_path "$HOME/.config/bash/aliases"
source_path "$HOME/.config/bash/functions"
source_path "/usr/share/fzf/shell/key-bindings.bash"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

eval "$(starship init bash)"
